### PR TITLE
Block rtxTimer.stop() until timer routine end

### LINKED ISSUE #129: Race found in travis-ci
Just from auto updating a lib https://github.com/pion/sctp/pull/128 

```
==================
WARNING: DATA RACE
Read at 0x00c000023f10 by goroutine 79:
  github.com/pion/sctp.TestRtxTimer.func4()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:206 +0x521
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199
Previous write at 0x00c000023f10 by goroutine 78:
  github.com/pion/sctp.TestRtxTimer.func4.1()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:188 +0x89
  github.com/pion/sctp.(*testTimerObserver).onRetransmissionTimeout()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:95 +0x5a
  github.com/pion/sctp.(*rtxTimer).start.func1()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer.go:155 +0x30d
Goroutine 79 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:960 +0x651
  github.com/pion/sctp.TestRtxTimer()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:183 +0xea
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199
Goroutine 78 (running) created at:
  github.com/pion/sctp.(*rtxTimer).start()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer.go:144 +0x1da
  github.com/pion/sctp.TestRtxTimer.func4()
      /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:199 +0x38f
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199
==================
```

### PR DESCRIPTION
**Pull request by at-wat**
Fix data race during TestRtxTimer.

### Reference issue
Fixes #129

### CODE REVIEW

**Comment by enobufs** [comment]
The build error appears to be complaining about the race on the variable `nCbs`.
The error log found in #129: 
```
 /home/travis/gopath/src/github.com/pion/sctp/rtx_timer_test.go:206 +0x521
```

I was able to reproduce the issue and fix this problem locally by using atomic methods for nCbs.  Let me send another PR.

**Comment by at-wat** [comment]
@enobufs Yes, accessing `nCbs` using atomic will also fix the race.

On the other hand, current master branch version has no way to know when the caller can assume that the handler will no longer be called. It may cause another race in real application not only the test code, IMO.

**Comment by enobufs** [comment]
I see.  Look like you are trying to address another problem and we could file another issue to address it later?

**Comment by at-wat** [comment]
Seems not mandatory.

**Pull request closed without merging**
