### PR TITLE
Implement draft-ietf-tsvwg-sctp-zero-checksum-01

### PR DESCRIPTION
**Pull request by mengelbart**
#### Description

Implementation of [draft-ietf-tsvwg-sctp-zero-checksum-01](https://datatracker.ietf.org/doc/html/draft-ietf-tsvwg-sctp-zero-checksum-01). 

I currently don't have a specific use case for this, but implementing the draft was an interesting exercise. I suggest keeping this as draft PR, at least until the document is finalized.

### CODE REVIEW

**Comment by tuexen** [comment]
Question, maybe also for @Sean-Der : What possibilities of collaboration do exist? Only by commenting or is there a way to propose changes to a PR?

**Comment by mengelbart** [comment]
Hi @tuexen! You can add suggestions in the comments (there's a little icon in the comments UI where you can directly suggest code changes), or I think you can also open a PR against this branch. I also don't mind if you directly push to this branch, but I think that only works if you are a member of the pion org. (if not, I think @Sean-Der can add you as a member?)

**Comment by Sean-Der** [comment]
Done! You can directly push to branches now @tuexen 

Everyone just needs one approval to merge to master :)

**Comment by tuexen** [comment]
> Done! You can directly push to branches now @tuexen

Great thanks. This makes things much simpler. 

> 
> Everyone just needs one approval to merge to master :)

Great. I'll be conservative, since I'm new to go...

**Comment by Sean-Der** [comment]
Anything I can do to help @mengelbart ? Seems like this is really close, would love to get it in :)

**Comment by mengelbart** [comment]
I think it is almost done. The IETF draft changed a bit since I first implemented it. I don't think it requires changes in this patch but someone should probably review that again. And I think the code needs to be reviewed in general :)

**Comment by daweifeng** [comment]
I have been using this branch in my project for a month and I haven't seen any issues so far. It is compatible with the C++ zero checksum implementation in [libdatachannel](https://github.com/paullouisageneau/libdatachannel)

**Comment by matthewfarstad** [comment]
Very excited for this to be merged. Until then I will be using the PR.

**Pull request merged**
